project:
  type: website
  output-dir: docs

website:
  title: "Sigma-Tau Blog"
  site-url: "fralfaro.github.io/blog/"
  favicon: 'images/sigma.png'
  image: 'images/sigma.png'
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Francisco Alfaro. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/Sigma-Tau
      - icon: linkedin
        href: https://www.linkedin.com/company/sigma-tau-chile
      - icon: globe
        href: https://sigma-tau.github.io/website/

    
  navbar:
    logo: /images/sigma.png
    right:
      - icon: github
        href: https://github.com/Sigma-Tau
      - icon: linkedin
        href: https://www.linkedin.com/company/sigma-tau-chile
      - icon: globe
        href: https://sigma-tau.github.io/website/


lang: es

format:
  html:
    smooth-scroll: true
    theme:
      light: [Lumen, stylesheets/custom2.scss]
      dark: [Lumen, stylesheets/custom2.scss, stylesheets/theme-dark.scss]
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

editor: visual

execute:
  freeze: true
